version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: quarkus_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: securedb
      POSTGRES_USER: quarkus
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: quarkus_keycloak
    command: start-dev
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

  kong-db:
    image: postgres:13
    container_name: kong_postgres
    environment:
      POSTGRES_DB: kong
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong
    ports:
      - "5433:5432"

  kong-migrations:
    image: kong/kong-gateway:3.6
    command: kong migrations bootstrap
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-db
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
    depends_on:
      - kong-db

  kong:
    image: kong/kong-gateway:3.6
    container_name: kong
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-db
      KONG_PG_PASSWORD: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
    ports:
      - "8000:8000"   # Public proxy
      - "8443:8443"   # Public proxy SSL
      - "8001:8001"   # Admin API
      - "8444:8444"   # Admin API SSL
    depends_on:
      - kong-db

volumes:
  pgdata:
